# Answer of Question no. 1 

In [2]:
import numpy as np
arr=np.arange(51)[2:51:3]
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# Answer of Question No. 2 

In [3]:
list1=[]
list2=[]

print("Enter the elements of list1: ")

for i in range(0,5):                      #Getting elements of List2 from user 
    list1.append(int(input()))
    
print("Enter the elements of list2: ")    #Getting elements of List2 from user   
for j in range(0,5):
    list2.append(int(input()))

print("The entered list are: ")
print(list1)
print(list2)                              

arr1 = np.array(list1)                  
arr2 = np.array(list2)                     #converting list1 and list2 into np arrays

print("The Arrays are:  ")
print(arr1)
print(arr2)                 

print("Concatenated Arrays: ")
arr3 = np.append(arr1,arr2,axis=0)
print(arr3)

print("After sorting :")
print(np.sort(arr3))

Enter the elements of list1: 
5
69
8
2
4
Enter the elements of list2: 
1
69
25
4
6
The entered list are: 
[5, 69, 8, 2, 4]
[1, 69, 25, 4, 6]
The Arrays are:  
[ 5 69  8  2  4]
[ 1 69 25  4  6]
Concatenated Arrays: 
[ 5 69  8  2  4  1 69 25  4  6]
After sorting :
[ 1  2  4  4  5  6  8 25 69 69]


# Answer of Question no. 3 

In [4]:
import numpy as np #imported only for testing purpose  
print("1D Array")
array_1d = np.arange(10)
print(array_1d)
print("The dimension is:",array_1d.ndim)
print("The size of the array is: ",array_1d.size)

print()
print("2D Array")
array_2d = np.arange(12).reshape((3,4))
print(array_2d)
print("The dimension is",array_2d.ndim)
print("The size of the array is: ",array_2d.size)

1D Array
[0 1 2 3 4 5 6 7 8 9]
The dimension is: 1
The size of the array is:  10

2D Array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
The dimension is 2
The size of the array is:  12


# Answer of Question no. 4

In [5]:
arry_1d = np.arange(9)
print("1D array")
print(arry_1d)

print("\n Convering into 2D array")
print(arry_1d.reshape(3,3))

1D array
[0 1 2 3 4 5 6 7 8]

 Convering into 2D array
[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Answer of Question no. 5 

In [14]:
import numpy as np
aray_1 = [1,2,5]
aray_2 = [8,5,9]
square_array1 = np.square(aray_1)
square_array2 = np.square(aray_2)
print("Square of Array 1:", square_array1, "\n The Vertical Stack of array is:", np.vstack((aray_1, aray_2)))

print("Square of Array 2 :", square_array2, "\n The Horizontal Stack of array is:", np.hstack((aray_1, aray_2)))

Square of Array 1: [ 1  4 25] 
 The Vertical Stack of array is: [[1 2 5]
 [8 5 9]]
Square of Array 2 : [64 25 81] 
 The Horizontal Stack of array is: [1 2 5 8 5 9]


In [16]:
"""
I solved question number 5 in two different ways becuase i didn't understand question. 
"""
a = np.array([[3, 4], 
              [8, 9]]) 
  
b = np.array([[3, 5], 
              [9, 3]]) 
  
print("Vertical stacking:\n", np.vstack((a, b))) # vertical stacking
  
print("\nHorizontal stacking:\n", np.hstack((a, b))) # horizontal stacking 
  
    
    

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]


# Answer of Question no 6

In [23]:
#Generating unique items 
import numpy as np 
def unique(uniq_1): 
    x = np.array(uniq_1) 
    print(np.unique(x)) 
      
  
unique_item1 = np.random.randint(1, 40, 10)
print("Generated Uniques Items1:", unique_item1)
print("\nThe unique values from 1st Unique item is") 
unique(unique_item1) 
  

Generated Uniques Items1: [ 3 15 30 21 14 23  9  3 31 24]

The unique values from 1st Unique item is
[ 3  9 14 15 21 23 24 30 31]
